### ISSUE TITLE
ajaxfileupload 文件上传进度问题

### ISSUE THREAD

**Issue by nickname-nil** [gaojr/ajaxfileupload#1]
你好，我也在用这个js
现在需要展示前端上传文件的进度条，我在想展示真实的上传进度，
却发现没有options对应progress，请问有没有办法

看到有很多在xhr中addeventlistener注册回调函数，但是这里好像不能用

**Comment by gaojr** [comment]
我改这东西的时间太久远了，而且单个文件的上传也不是很需要进度条，建议你自力更生 🤣

btw 你说的 xhr.addeventlistener() 方法是根据 xhr 的状态来绑定回调的，单文件上传的情况下，这个方法没法实现你要的进度条
